### PR TITLE
Do not use trailing comma

### PR DESCRIPTION
**Pull request by daynin**
Node.js 7 does not support a trailing comman in an agruments of a
function

### CODE REVIEW

**Comment by Laiff** [comment]
Can you add build matrix in `travis.yml` for check this by default

**Comment by daynin** [comment]
@Laiff why you want to use a build matrix? Rispa is not a transpiled project which can be built into few versions of node.js, is it? So, we can just add a simple rule into eslint conf and solve a backward compatibility issue. And it will work for 7 and 8 versions of node.js

Or I misunderstood your suggestion?

**Comment by daynin** [comment]
@Laiff I've just added a eslint rule to check a trailing comma in arguments of a function and then fix all of it by `npm run lint:fix`

**Review by Laiff — APPROVED** [review]

**Comment by Laiff** [comment]
[113. Crash on node 7.10](https://trello.com/c/HBm9pBXf/113-113-crash-on-node-710)

**Pull request merged**
